runtime: nodejs
env: flex
service: api-photosub
env_variables:
  NODE_ENV: production
  DB_DATABASE: xxxxxx
  DB_USER: xxx
  DB_PASS: xxxxxxxxxx
  DB_SOCKET_PATH: /cloudsql
  CLOUD_SQL_CONNECTION_NAME: xxxxxxxxxxxxxxxx
beta_settings:
  cloud_sql_instances: xxxxxxxxxxxxxx
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
